set -g mouse on 
set -g default-terminal "tmux-256color"
set-window-option -g mode-keys vi

set-option -g status-position top

# Change Prefix here
# unbind C-b
# set -g prefix2 C-space
# bind C-space send-prefix -2
set -g prefix2 ²
bind ² send-prefix -2

unbind r
bind r source-file ~/.tmux.conf

# vim movements
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# panes split
unbind e
bind e split-window -v
unbind o 
bind o split-window -h

# Popup
unbind t #normally its "show a clock"
bind-key t display-popup -E -w 60% -h 60% "~/.tmux/scripts/session-picker.sh"
bind-key g display-popup -E -d '#{pane_current_path}' -w 90% -h 90% "pwd && lazygit"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'catppuccin/tmux'

# resurrect config
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'
set -g @resurrect-capture-pane-contents 'on'
# continuum (must be after resurrect)
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
set -g @continuum-save 'on'

# catpuccin config
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"

# Load catppuccin
run ~/.tmux/plugins/tmux/catppuccin.tmux

set -g allow-rename off
set-window-option -g automatic-rename off

# Longueur status bar
set -g status-left-length 100
set -g status-right-length 100

# Texte des fenêtres (corrigé)
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"

# Gauche : session + app + zoom flag
set -g status-left "#{E:@catppuccin_status_session}"
set -agF status-left "#{E:@catppuccin_status_application}"
set -ag status-left "#{?window_zoomed_flag,#[fg=red][Z] #[default],}"

# Affichage des fenêtres (laisser Catppuccin gérer)
set -agF status-left "#{E:@catppuccin_status_window}"

# (Optionnel) commente si conflit avec le thème
# set -g window-status-current-format "#[fg=colour231,bold]#W"
# set -g window-status-format "#[fg=colour245]#W"

# Droite : modules
set -g status-right ""
set -agF status-right "#{E:@catppuccin_status_battery}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -agF status-right "#{E:@catppuccin_status_ram}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
# set -agF status-right "#{E:@catppuccin_status_continuum}"

# Split en gardant le path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

run '~/.tmux/plugins/tpm/tpm'
